/**
 * warning: this file is generated by tarat. do not modified this file
 */
import React from "react";
import { Routes, Route } from "react-router-dom";
import { StaticRouter } from "react-router-dom/server";

import { setHookAdaptor, registerModelIndexes } from "@polymita/connect";

export { getReactAdaptor } from "@polymita/connect";

setHookAdaptor(React);

import "/Users/zhouyunge/Documents/fishpond-desktop-workspace/packages/polymita-runtime/packages/example/file-uploader/app/entry.css";

import App from "/Users/zhouyunge/Documents/fishpond-desktop-workspace/packages/polymita-runtime/packages/example/file-uploader/app/_app";

import Main from "/Users/zhouyunge/Documents/fishpond-desktop-workspace/packages/polymita-runtime/packages/example/file-uploader/app/pages/main";

registerModelIndexes({
  uploaderItem: "uploaderItem",
});

export default function _TaratRootApplication({ location }) {
  return (
    <StaticRouter location={location}>
      <App>
        <Routes>
          <Route path="main" element={<Main />}></Route>
        </Routes>
      </App>
    </StaticRouter>
  );
}
