export const injectTagStart = '/**. auto generated */'
export const injectTagEnd = '/** auto generated .*/'

export const autoGeneratedFileTag = 'auto generated file'

export const autoGeneratedTip = () => [
  '//',
  `// ${autoGeneratedFileTag}`,
  '// provide by',
  '// warning: auto generated . Do not modify this file',
  '//'
]

